import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Movies Inc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentYear = new Date().getUTCFullYear();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-row gap-1 justify-center items-center py-4">
          <h1 className="text-3xl font-bold">Movies Inc</h1>
          <span className="text-xs bg-black/60">by Adriano</span>
        </header>
        <main className="flex flex-col justify-center items-center max-w-7xl px-8 pt-16 lg:mr-auto lg:ml-auto">
          {children}
        </main>
        <footer className="flex px-6 py-16 flex-wrap items-center justify-center">
          <span className="text-xs text-center sm:text-left">© {currentYear} Movies Inc</span>
        </footer>
      </body>
    </html>
  );
}
